# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.link_amount import LinkAmount
from openapi_server import util

from openapi_server.models.link_amount import LinkAmount  # noqa: E501

class InlineObject1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, amount=None, offer_code=None, airline=None):  # noqa: E501
        """InlineObject1 - a model defined in OpenAPI

        :param amount: The amount of this InlineObject1.  # noqa: E501
        :type amount: LinkAmount
        :param offer_code: The offer_code of this InlineObject1.  # noqa: E501
        :type offer_code: str
        :param airline: The airline of this InlineObject1.  # noqa: E501
        :type airline: str
        """
        self.openapi_types = {
            'amount': LinkAmount,
            'offer_code': str,
            'airline': str
        }

        self.attribute_map = {
            'amount': 'amount',
            'offer_code': 'offer_code',
            'airline': 'airline'
        }

        self._amount = amount
        self._offer_code = offer_code
        self._airline = airline

    @classmethod
    def from_dict(cls, dikt) -> 'InlineObject1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object_1 of this InlineObject1.  # noqa: E501
        :rtype: InlineObject1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount(self):
        """Gets the amount of this InlineObject1.


        :return: The amount of this InlineObject1.
        :rtype: LinkAmount
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this InlineObject1.


        :param amount: The amount of this InlineObject1.
        :type amount: LinkAmount
        """

        self._amount = amount

    @property
    def offer_code(self):
        """Gets the offer_code of this InlineObject1.

        Codice dell'offerta che il cliente intende acquistare: in dettaglio, questo codice non è quello identificante la coppia offerta - cliente, bensì è quello assegnato, in principio, all'offerta dalla compagnia aerea che l'ha attivata, ancor prima di comunicarla ad ACMESky.  Quando il fornitore dei servizi bancari inoltrerà la quota del pagamento del cliente alla compagnia aerea, le invierà anche questo codice per comunicarle l'offerta di cui le sta inviando il pagamento.  # noqa: E501

        :return: The offer_code of this InlineObject1.
        :rtype: str
        """
        return self._offer_code

    @offer_code.setter
    def offer_code(self, offer_code):
        """Sets the offer_code of this InlineObject1.

        Codice dell'offerta che il cliente intende acquistare: in dettaglio, questo codice non è quello identificante la coppia offerta - cliente, bensì è quello assegnato, in principio, all'offerta dalla compagnia aerea che l'ha attivata, ancor prima di comunicarla ad ACMESky.  Quando il fornitore dei servizi bancari inoltrerà la quota del pagamento del cliente alla compagnia aerea, le invierà anche questo codice per comunicarle l'offerta di cui le sta inviando il pagamento.  # noqa: E501

        :param offer_code: The offer_code of this InlineObject1.
        :type offer_code: str
        """

        self._offer_code = offer_code

    @property
    def airline(self):
        """Gets the airline of this InlineObject1.

        Compagnia aerea che ha attivato l'offerta per il cui pagamento si chiede la generazione del link: servirà al fornitore dei servizi bancari per inoltrarle la quota spettante.  # noqa: E501

        :return: The airline of this InlineObject1.
        :rtype: str
        """
        return self._airline

    @airline.setter
    def airline(self, airline):
        """Sets the airline of this InlineObject1.

        Compagnia aerea che ha attivato l'offerta per il cui pagamento si chiede la generazione del link: servirà al fornitore dei servizi bancari per inoltrarle la quota spettante.  # noqa: E501

        :param airline: The airline of this InlineObject1.
        :type airline: str
        """

        self._airline = airline
