# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineResponse200Price(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, amount=None, currency=None):  # noqa: E501
        """InlineResponse200Price - a model defined in OpenAPI

        :param amount: The amount of this InlineResponse200Price.  # noqa: E501
        :type amount: float
        :param currency: The currency of this InlineResponse200Price.  # noqa: E501
        :type currency: str
        """
        self.openapi_types = {
            'amount': float,
            'currency': str
        }

        self.attribute_map = {
            'amount': 'amount',
            'currency': 'currency'
        }

        self._amount = amount
        self._currency = currency

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Price':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_price of this InlineResponse200Price.  # noqa: E501
        :rtype: InlineResponse200Price
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount(self):
        """Gets the amount of this InlineResponse200Price.


        :return: The amount of this InlineResponse200Price.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this InlineResponse200Price.


        :param amount: The amount of this InlineResponse200Price.
        :type amount: float
        """

        self._amount = amount

    @property
    def currency(self):
        """Gets the currency of this InlineResponse200Price.


        :return: The currency of this InlineResponse200Price.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this InlineResponse200Price.


        :param currency: The currency of this InlineResponse200Price.
        :type currency: str
        """

        self._currency = currency
