# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2001_data import InlineResponse2001Data  # noqa: F401,E501
from swagger_server.models.inline_response2001_links import InlineResponse2001Links  # noqa: F401,E501
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: InlineResponse2001Data=None, links: InlineResponse2001Links=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param data: The data of this InlineResponse2001.  # noqa: E501
        :type data: InlineResponse2001Data
        :param links: The links of this InlineResponse2001.  # noqa: E501
        :type links: InlineResponse2001Links
        """
        self.swagger_types = {
            'data': InlineResponse2001Data,
            'links': InlineResponse2001Links
        }

        self.attribute_map = {
            'data': 'data',
            'links': 'links'
        }
        self._data = data
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> InlineResponse2001Data:
        """Gets the data of this InlineResponse2001.


        :return: The data of this InlineResponse2001.
        :rtype: InlineResponse2001Data
        """
        return self._data

    @data.setter
    def data(self, data: InlineResponse2001Data):
        """Sets the data of this InlineResponse2001.


        :param data: The data of this InlineResponse2001.
        :type data: InlineResponse2001Data
        """

        self._data = data

    @property
    def links(self) -> InlineResponse2001Links:
        """Gets the links of this InlineResponse2001.


        :return: The links of this InlineResponse2001.
        :rtype: InlineResponse2001Links
        """
        return self._links

    @links.setter
    def links(self, links: InlineResponse2001Links):
        """Sets the links of this InlineResponse2001.


        :param links: The links of this InlineResponse2001.
        :type links: InlineResponse2001Links
        """

        self._links = links
