# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.offer_message import OfferMessage  # noqa: F401,E501
from swagger_server import util


class InlineResponse200Message(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, offer: OfferMessage=None, receiver: str=None, _date: str=None, id: int=None):  # noqa: E501
        """InlineResponse200Message - a model defined in Swagger

        :param offer: The offer of this InlineResponse200Message.  # noqa: E501
        :type offer: OfferMessage
        :param receiver: The receiver of this InlineResponse200Message.  # noqa: E501
        :type receiver: str
        :param _date: The _date of this InlineResponse200Message.  # noqa: E501
        :type _date: str
        :param id: The id of this InlineResponse200Message.  # noqa: E501
        :type id: int
        """
        self.swagger_types = {
            'offer': OfferMessage,
            'receiver': str,
            '_date': str,
            'id': int
        }

        self.attribute_map = {
            'offer': 'offer',
            'receiver': 'receiver',
            '_date': 'date',
            'id': 'id'
        }
        self._offer = offer
        self._receiver = receiver
        self.__date = _date
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Message':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_message of this InlineResponse200Message.  # noqa: E501
        :rtype: InlineResponse200Message
        """
        return util.deserialize_model(dikt, cls)

    @property
    def offer(self) -> OfferMessage:
        """Gets the offer of this InlineResponse200Message.


        :return: The offer of this InlineResponse200Message.
        :rtype: OfferMessage
        """
        return self._offer

    @offer.setter
    def offer(self, offer: OfferMessage):
        """Sets the offer of this InlineResponse200Message.


        :param offer: The offer of this InlineResponse200Message.
        :type offer: OfferMessage
        """

        self._offer = offer

    @property
    def receiver(self) -> str:
        """Gets the receiver of this InlineResponse200Message.


        :return: The receiver of this InlineResponse200Message.
        :rtype: str
        """
        return self._receiver

    @receiver.setter
    def receiver(self, receiver: str):
        """Sets the receiver of this InlineResponse200Message.


        :param receiver: The receiver of this InlineResponse200Message.
        :type receiver: str
        """

        self._receiver = receiver

    @property
    def _date(self) -> str:
        """Gets the _date of this InlineResponse200Message.


        :return: The _date of this InlineResponse200Message.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this InlineResponse200Message.


        :param _date: The _date of this InlineResponse200Message.
        :type _date: str
        """

        self.__date = _date

    @property
    def id(self) -> int:
        """Gets the id of this InlineResponse200Message.


        :return: The id of this InlineResponse200Message.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this InlineResponse200Message.


        :param id: The id of this InlineResponse200Message.
        :type id: int
        """

        self._id = id
