# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.register_data import RegisterData  # noqa: F401,E501
from swagger_server import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: RegisterData=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param data: The data of this Body.  # noqa: E501
        :type data: RegisterData
        """
        self.swagger_types = {
            'data': RegisterData
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> RegisterData:
        """Gets the data of this Body.


        :return: The data of this Body.
        :rtype: RegisterData
        """
        return self._data

    @data.setter
    def data(self, data: RegisterData):
        """Sets the data of this Body.


        :param data: The data of this Body.
        :type data: RegisterData
        """

        self._data = data
