# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2001_data_links import InlineResponse2001DataLinks  # noqa: F401,E501
from swagger_server.models.offer_message import OfferMessage  # noqa: F401,E501
from swagger_server import util


class InlineResponse2001DataMessage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, offer: OfferMessage=None, _date: str=None, links: InlineResponse2001DataLinks=None, id: int=None):  # noqa: E501
        """InlineResponse2001DataMessage - a model defined in Swagger

        :param offer: The offer of this InlineResponse2001DataMessage.  # noqa: E501
        :type offer: OfferMessage
        :param _date: The _date of this InlineResponse2001DataMessage.  # noqa: E501
        :type _date: str
        :param links: The links of this InlineResponse2001DataMessage.  # noqa: E501
        :type links: InlineResponse2001DataLinks
        :param id: The id of this InlineResponse2001DataMessage.  # noqa: E501
        :type id: int
        """
        self.swagger_types = {
            'offer': OfferMessage,
            '_date': str,
            'links': InlineResponse2001DataLinks,
            'id': int
        }

        self.attribute_map = {
            'offer': 'offer',
            '_date': 'date',
            'links': 'links',
            'id': 'id'
        }
        self._offer = offer
        self.__date = _date
        self._links = links
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001DataMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1_data_message of this InlineResponse2001DataMessage.  # noqa: E501
        :rtype: InlineResponse2001DataMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def offer(self) -> OfferMessage:
        """Gets the offer of this InlineResponse2001DataMessage.


        :return: The offer of this InlineResponse2001DataMessage.
        :rtype: OfferMessage
        """
        return self._offer

    @offer.setter
    def offer(self, offer: OfferMessage):
        """Sets the offer of this InlineResponse2001DataMessage.


        :param offer: The offer of this InlineResponse2001DataMessage.
        :type offer: OfferMessage
        """

        self._offer = offer

    @property
    def _date(self) -> str:
        """Gets the _date of this InlineResponse2001DataMessage.


        :return: The _date of this InlineResponse2001DataMessage.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this InlineResponse2001DataMessage.


        :param _date: The _date of this InlineResponse2001DataMessage.
        :type _date: str
        """

        self.__date = _date

    @property
    def links(self) -> InlineResponse2001DataLinks:
        """Gets the links of this InlineResponse2001DataMessage.


        :return: The links of this InlineResponse2001DataMessage.
        :rtype: InlineResponse2001DataLinks
        """
        return self._links

    @links.setter
    def links(self, links: InlineResponse2001DataLinks):
        """Sets the links of this InlineResponse2001DataMessage.


        :param links: The links of this InlineResponse2001DataMessage.
        :type links: InlineResponse2001DataLinks
        """

        self._links = links

    @property
    def id(self) -> int:
        """Gets the id of this InlineResponse2001DataMessage.


        :return: The id of this InlineResponse2001DataMessage.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this InlineResponse2001DataMessage.


        :param id: The id of this InlineResponse2001DataMessage.
        :type id: int
        """

        self._id = id
