/*
 * prontogramAPI
 * È l'API Restful offerta dall'applicazione di messaggistica *Prontogram* che vi racchiude la capability di inoltrare i messaggi circa le offerte inviate da ACMESky ai clienti interessati.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package prontogramprovider.prontogram_client;

import prontogramprovider.ApiException;
import io.swagger.client.model.RegisterBody;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Registra un nuovo utente
     *
     * Registra un nuovo utente; prende in input solo un nome utente e una password
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postRegisterTest() throws ApiException {
        RegisterBody body = null;
        api.postRegister(body);

        // TODO: test validations
    }
}
