/*
 * compagniaAereaAPI
 * È l'API Restful offerta dalla compagnia aerea che permette di restituire le offerte attive, creare voli last minute e di ricevere la quota del pagamento del cliente.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.LMflightFlight;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse200
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-10-06T11:44:12.432+02:00[Europe/Rome]")
public class InlineResponse200 {
  @SerializedName("flights")
  private List<LMflightFlight> flights = null;

  @SerializedName("companyname")
  private String companyname = null;

  public InlineResponse200 flights(List<LMflightFlight> flights) {
    this.flights = flights;
    return this;
  }

  public InlineResponse200 addFlightsItem(LMflightFlight flightsItem) {
    if (this.flights == null) {
      this.flights = new ArrayList<LMflightFlight>();
    }
    this.flights.add(flightsItem);
    return this;
  }

   /**
   * Get flights
   * @return flights
  **/
  @Schema(description = "")
  public List<LMflightFlight> getFlights() {
    return flights;
  }

  public void setFlights(List<LMflightFlight> flights) {
    this.flights = flights;
  }

  public InlineResponse200 companyname(String companyname) {
    this.companyname = companyname;
    return this;
  }

   /**
   * Get companyname
   * @return companyname
  **/
  @Schema(description = "")
  public String getCompanyname() {
    return companyname;
  }

  public void setCompanyname(String companyname) {
    this.companyname = companyname;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.flights, inlineResponse200.flights) &&
        Objects.equals(this.companyname, inlineResponse200.companyname);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flights, companyname);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("    flights: ").append(toIndentedString(flights)).append("\n");
    sb.append("    companyname: ").append(toIndentedString(companyname)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
