# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.createmessage_data import CreatemessageData  # noqa: F401,E501
from swagger_server import util


class Message(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: CreatemessageData=None):  # noqa: E501
        """Message - a model defined in Swagger

        :param data: The data of this Message.  # noqa: E501
        :type data: CreatemessageData
        """
        self.swagger_types = {
            'data': CreatemessageData
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'Message':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The message of this Message.  # noqa: E501
        :rtype: Message
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> CreatemessageData:
        """Gets the data of this Message.


        :return: The data of this Message.
        :rtype: CreatemessageData
        """
        return self._data

    @data.setter
    def data(self, data: CreatemessageData):
        """Sets the data of this Message.


        :param data: The data of this Message.
        :type data: CreatemessageData
        """

        self._data = data
