# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NotifypaymentTransaction(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: str=None, id: float=None):  # noqa: E501
        """NotifypaymentTransaction - a model defined in Swagger

        :param _date: The _date of this NotifypaymentTransaction.  # noqa: E501
        :type _date: str
        :param id: The id of this NotifypaymentTransaction.  # noqa: E501
        :type id: float
        """
        self.swagger_types = {
            '_date': str,
            'id': float
        }

        self.attribute_map = {
            '_date': 'date',
            'id': 'id'
        }
        self.__date = _date
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'NotifypaymentTransaction':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The notifypayment_transaction of this NotifypaymentTransaction.  # noqa: E501
        :rtype: NotifypaymentTransaction
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> str:
        """Gets the _date of this NotifypaymentTransaction.


        :return: The _date of this NotifypaymentTransaction.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this NotifypaymentTransaction.


        :param _date: The _date of this NotifypaymentTransaction.
        :type _date: str
        """

        self.__date = _date

    @property
    def id(self) -> float:
        """Gets the id of this NotifypaymentTransaction.


        :return: The id of this NotifypaymentTransaction.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id: float):
        """Sets the id of this NotifypaymentTransaction.


        :param id: The id of this NotifypaymentTransaction.
        :type id: float
        """

        self._id = id
