/*
 * serviziBancariAPI
 * È l'API Restful offerta dal *fornitore dei servizi bancari* che rende accessibile la capability di generazione di un link di pagamento con certi parametri e di ricevere dati relativi al pagamento di un cliente.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.PaymentdataExpiration;
import io.swagger.client.model.PaymentdataTransaction;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Body
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-20T16:01:27.643+02:00[Europe/Rome]")
public class Body {
  @SerializedName("card_number")
  private Integer cardNumber = null;

  @SerializedName("expiration")
  private PaymentdataExpiration expiration = null;

  @SerializedName("CVC")
  private Integer CVC = null;

  @SerializedName("circuit")
  private String circuit = null;

  @SerializedName("transaction")
  private PaymentdataTransaction transaction = null;

  public Body cardNumber(Integer cardNumber) {
    this.cardNumber = cardNumber;
    return this;
  }

   /**
   * Get cardNumber
   * @return cardNumber
  **/
  @Schema(description = "")
  public Integer getCardNumber() {
    return cardNumber;
  }

  public void setCardNumber(Integer cardNumber) {
    this.cardNumber = cardNumber;
  }

  public Body expiration(PaymentdataExpiration expiration) {
    this.expiration = expiration;
    return this;
  }

   /**
   * Get expiration
   * @return expiration
  **/
  @Schema(description = "")
  public PaymentdataExpiration getExpiration() {
    return expiration;
  }

  public void setExpiration(PaymentdataExpiration expiration) {
    this.expiration = expiration;
  }

  public Body CVC(Integer CVC) {
    this.CVC = CVC;
    return this;
  }

   /**
   * Get CVC
   * @return CVC
  **/
  @Schema(description = "")
  public Integer getCVC() {
    return CVC;
  }

  public void setCVC(Integer CVC) {
    this.CVC = CVC;
  }

  public Body circuit(String circuit) {
    this.circuit = circuit;
    return this;
  }

   /**
   * Get circuit
   * @return circuit
  **/
  @Schema(description = "")
  public String getCircuit() {
    return circuit;
  }

  public void setCircuit(String circuit) {
    this.circuit = circuit;
  }

  public Body transaction(PaymentdataTransaction transaction) {
    this.transaction = transaction;
    return this;
  }

   /**
   * Get transaction
   * @return transaction
  **/
  @Schema(description = "")
  public PaymentdataTransaction getTransaction() {
    return transaction;
  }

  public void setTransaction(PaymentdataTransaction transaction) {
    this.transaction = transaction;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body body = (Body) o;
    return Objects.equals(this.cardNumber, body.cardNumber) &&
        Objects.equals(this.expiration, body.expiration) &&
        Objects.equals(this.CVC, body.CVC) &&
        Objects.equals(this.circuit, body.circuit) &&
        Objects.equals(this.transaction, body.transaction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardNumber, expiration, CVC, circuit, transaction);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body {\n");
    
    sb.append("    cardNumber: ").append(toIndentedString(cardNumber)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    CVC: ").append(toIndentedString(CVC)).append("\n");
    sb.append("    circuit: ").append(toIndentedString(circuit)).append("\n");
    sb.append("    transaction: ").append(toIndentedString(transaction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
