/*
 * serviziBancariAPI
 * È l'API Restful offerta dal *fornitore dei servizi bancari* che rende accessibile la capability di generazione di un codice di pagamento con certi parametri e di ricevere dati relativi al pagamento di un cliente.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.LinkAmount;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * LinkBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-10-07T00:10:42.524+02:00[Europe/Rome]")
public class LinkBody {
  @SerializedName("amount")
  private LinkAmount amount = null;

  @SerializedName("offer_code")
  private String offerCode = null;

  @SerializedName("airline")
  private String airline = null;

  public LinkBody amount(LinkAmount amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @Schema(description = "")
  public LinkAmount getAmount() {
    return amount;
  }

  public void setAmount(LinkAmount amount) {
    this.amount = amount;
  }

  public LinkBody offerCode(String offerCode) {
    this.offerCode = offerCode;
    return this;
  }

   /**
   * Codice dell&#x27;offerta che il cliente intende acquistare: in dettaglio, questo codice non è quello identificante la coppia offerta - cliente, bensì è quello assegnato, in principio, all&#x27;offerta dalla compagnia aerea che l&#x27;ha attivata, ancor prima di comunicarla ad ACMESky.  Quando il fornitore dei servizi bancari inoltrerà la quota del pagamento del cliente alla compagnia aerea, le invierà anche questo codice per comunicarle l&#x27;offerta di cui le sta inviando il pagamento.
   * @return offerCode
  **/
  @Schema(description = "Codice dell'offerta che il cliente intende acquistare: in dettaglio, questo codice non è quello identificante la coppia offerta - cliente, bensì è quello assegnato, in principio, all'offerta dalla compagnia aerea che l'ha attivata, ancor prima di comunicarla ad ACMESky.  Quando il fornitore dei servizi bancari inoltrerà la quota del pagamento del cliente alla compagnia aerea, le invierà anche questo codice per comunicarle l'offerta di cui le sta inviando il pagamento.")
  public String getOfferCode() {
    return offerCode;
  }

  public void setOfferCode(String offerCode) {
    this.offerCode = offerCode;
  }

  public LinkBody airline(String airline) {
    this.airline = airline;
    return this;
  }

   /**
   * Compagnia aerea che ha attivato l&#x27;offerta per il cui pagamento si chiede la generazione del link: servirà al fornitore dei servizi bancari per inoltrarle la quota spettante.
   * @return airline
  **/
  @Schema(description = "Compagnia aerea che ha attivato l'offerta per il cui pagamento si chiede la generazione del link: servirà al fornitore dei servizi bancari per inoltrarle la quota spettante.")
  public String getAirline() {
    return airline;
  }

  public void setAirline(String airline) {
    this.airline = airline;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkBody linkBody = (LinkBody) o;
    return Objects.equals(this.amount, linkBody.amount) &&
        Objects.equals(this.offerCode, linkBody.offerCode) &&
        Objects.equals(this.airline, linkBody.airline);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, offerCode, airline);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkBody {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    offerCode: ").append(toIndentedString(offerCode)).append("\n");
    sb.append("    airline: ").append(toIndentedString(airline)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
