# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.inline_response200_flights import InlineResponse200Flights
from openapi_server import util

from openapi_server.models.inline_response200_flights import InlineResponse200Flights  # noqa: E501

class InlineResponse200(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, flights=None, companyname=None):  # noqa: E501
        """InlineResponse200 - a model defined in OpenAPI

        :param flights: The flights of this InlineResponse200.  # noqa: E501
        :type flights: List[InlineResponse200Flights]
        :param companyname: The companyname of this InlineResponse200.  # noqa: E501
        :type companyname: str
        """
        self.openapi_types = {
            'flights': List[InlineResponse200Flights],
            'companyname': str
        }

        self.attribute_map = {
            'flights': 'flights',
            'companyname': 'companyname'
        }

        self._flights = flights
        self._companyname = companyname

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def flights(self):
        """Gets the flights of this InlineResponse200.


        :return: The flights of this InlineResponse200.
        :rtype: List[InlineResponse200Flights]
        """
        return self._flights

    @flights.setter
    def flights(self, flights):
        """Sets the flights of this InlineResponse200.


        :param flights: The flights of this InlineResponse200.
        :type flights: List[InlineResponse200Flights]
        """

        self._flights = flights

    @property
    def companyname(self):
        """Gets the companyname of this InlineResponse200.


        :return: The companyname of this InlineResponse200.
        :rtype: str
        """
        return self._companyname

    @companyname.setter
    def companyname(self, companyname):
        """Sets the companyname of this InlineResponse200.


        :param companyname: The companyname of this InlineResponse200.
        :type companyname: str
        """

        self._companyname = companyname
