# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.inline_response200_flights import InlineResponse200Flights
from openapi_server import util

from openapi_server.models.inline_response200_flights import InlineResponse200Flights  # noqa: E501

class Lmflight(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, flight=None, companyname=None):  # noqa: E501
        """Lmflight - a model defined in OpenAPI

        :param flight: The flight of this Lmflight.  # noqa: E501
        :type flight: InlineResponse200Flights
        :param companyname: The companyname of this Lmflight.  # noqa: E501
        :type companyname: str
        """
        self.openapi_types = {
            'flight': InlineResponse200Flights,
            'companyname': str
        }

        self.attribute_map = {
            'flight': 'flight',
            'companyname': 'companyname'
        }

        self._flight = flight
        self._companyname = companyname

    @classmethod
    def from_dict(cls, dikt) -> 'Lmflight':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The lmflight of this Lmflight.  # noqa: E501
        :rtype: Lmflight
        """
        return util.deserialize_model(dikt, cls)

    @property
    def flight(self):
        """Gets the flight of this Lmflight.


        :return: The flight of this Lmflight.
        :rtype: InlineResponse200Flights
        """
        return self._flight

    @flight.setter
    def flight(self, flight):
        """Sets the flight of this Lmflight.


        :param flight: The flight of this Lmflight.
        :type flight: InlineResponse200Flights
        """

        self._flight = flight

    @property
    def companyname(self):
        """Gets the companyname of this Lmflight.


        :return: The companyname of this Lmflight.
        :rtype: str
        """
        return self._companyname

    @companyname.setter
    def companyname(self, companyname):
        """Sets the companyname of this Lmflight.


        :param companyname: The companyname of this Lmflight.
        :type companyname: str
        """

        self._companyname = companyname
