# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.inline_response2001_data_links import InlineResponse2001DataLinks
from openapi_server.models.offer_message import OfferMessage
from openapi_server import util

from openapi_server.models.inline_response2001_data_links import InlineResponse2001DataLinks  # noqa: E501
from openapi_server.models.offer_message import OfferMessage  # noqa: E501

class InlineResponse2001DataMessage(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, offer=None, date=None, links=None, id=None):  # noqa: E501
        """InlineResponse2001DataMessage - a model defined in OpenAPI

        :param offer: The offer of this InlineResponse2001DataMessage.  # noqa: E501
        :type offer: OfferMessage
        :param date: The date of this InlineResponse2001DataMessage.  # noqa: E501
        :type date: str
        :param links: The links of this InlineResponse2001DataMessage.  # noqa: E501
        :type links: InlineResponse2001DataLinks
        :param id: The id of this InlineResponse2001DataMessage.  # noqa: E501
        :type id: int
        """
        self.openapi_types = {
            'offer': OfferMessage,
            'date': str,
            'links': InlineResponse2001DataLinks,
            'id': int
        }

        self.attribute_map = {
            'offer': 'offer',
            'date': 'date',
            'links': 'links',
            'id': 'id'
        }

        self._offer = offer
        self._date = date
        self._links = links
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001DataMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1_data_message of this InlineResponse2001DataMessage.  # noqa: E501
        :rtype: InlineResponse2001DataMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def offer(self):
        """Gets the offer of this InlineResponse2001DataMessage.


        :return: The offer of this InlineResponse2001DataMessage.
        :rtype: OfferMessage
        """
        return self._offer

    @offer.setter
    def offer(self, offer):
        """Sets the offer of this InlineResponse2001DataMessage.


        :param offer: The offer of this InlineResponse2001DataMessage.
        :type offer: OfferMessage
        """

        self._offer = offer

    @property
    def date(self):
        """Gets the date of this InlineResponse2001DataMessage.


        :return: The date of this InlineResponse2001DataMessage.
        :rtype: str
        """
        return self._date

    @date.setter
    def date(self, date):
        """Sets the date of this InlineResponse2001DataMessage.


        :param date: The date of this InlineResponse2001DataMessage.
        :type date: str
        """

        self._date = date

    @property
    def links(self):
        """Gets the links of this InlineResponse2001DataMessage.


        :return: The links of this InlineResponse2001DataMessage.
        :rtype: InlineResponse2001DataLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this InlineResponse2001DataMessage.


        :param links: The links of this InlineResponse2001DataMessage.
        :type links: InlineResponse2001DataLinks
        """

        self._links = links

    @property
    def id(self):
        """Gets the id of this InlineResponse2001DataMessage.


        :return: The id of this InlineResponse2001DataMessage.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse2001DataMessage.


        :param id: The id of this InlineResponse2001DataMessage.
        :type id: int
        """

        self._id = id
