# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.inline_response200_links1 import InlineResponse200Links1
from openapi_server.models.inline_response200_message import InlineResponse200Message
from openapi_server import util

from openapi_server.models.inline_response200_links1 import InlineResponse200Links1  # noqa: E501
from openapi_server.models.inline_response200_message import InlineResponse200Message  # noqa: E501

class InlineResponse200Data(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None, links=None):  # noqa: E501
        """InlineResponse200Data - a model defined in OpenAPI

        :param message: The message of this InlineResponse200Data.  # noqa: E501
        :type message: InlineResponse200Message
        :param links: The links of this InlineResponse200Data.  # noqa: E501
        :type links: InlineResponse200Links1
        """
        self.openapi_types = {
            'message': InlineResponse200Message,
            'links': InlineResponse200Links1
        }

        self.attribute_map = {
            'message': 'message',
            'links': 'links'
        }

        self._message = message
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Data':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_data of this InlineResponse200Data.  # noqa: E501
        :rtype: InlineResponse200Data
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self):
        """Gets the message of this InlineResponse200Data.


        :return: The message of this InlineResponse200Data.
        :rtype: InlineResponse200Message
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this InlineResponse200Data.


        :param message: The message of this InlineResponse200Data.
        :type message: InlineResponse200Message
        """

        self._message = message

    @property
    def links(self):
        """Gets the links of this InlineResponse200Data.


        :return: The links of this InlineResponse200Data.
        :rtype: InlineResponse200Links1
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this InlineResponse200Data.


        :param links: The links of this InlineResponse200Data.
        :type links: InlineResponse200Links1
        """

        self._links = links
