# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.inline_response2001_data_message import InlineResponse2001DataMessage
from openapi_server import util

from openapi_server.models.inline_response2001_data_message import InlineResponse2001DataMessage  # noqa: E501

class InlineResponse2001Data(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None):  # noqa: E501
        """InlineResponse2001Data - a model defined in OpenAPI

        :param message: The message of this InlineResponse2001Data.  # noqa: E501
        :type message: List[InlineResponse2001DataMessage]
        """
        self.openapi_types = {
            'message': List[InlineResponse2001DataMessage]
        }

        self.attribute_map = {
            'message': 'message'
        }

        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001Data':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1_data of this InlineResponse2001Data.  # noqa: E501
        :rtype: InlineResponse2001Data
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self):
        """Gets the message of this InlineResponse2001Data.


        :return: The message of this InlineResponse2001Data.
        :rtype: List[InlineResponse2001DataMessage]
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this InlineResponse2001Data.


        :param message: The message of this InlineResponse2001Data.
        :type message: List[InlineResponse2001DataMessage]
        """

        self._message = message
