# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineObject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, point_a=None, points_b=None):  # noqa: E501
        """InlineObject - a model defined in OpenAPI

        :param point_a: The point_a of this InlineObject.  # noqa: E501
        :type point_a: str
        :param points_b: The points_b of this InlineObject.  # noqa: E501
        :type points_b: List[str]
        """
        self.openapi_types = {
            'point_a': str,
            'points_b': List[str]
        }

        self.attribute_map = {
            'point_a': 'pointA',
            'points_b': 'pointsB'
        }

        self._point_a = point_a
        self._points_b = points_b

    @classmethod
    def from_dict(cls, dikt) -> 'InlineObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object of this InlineObject.  # noqa: E501
        :rtype: InlineObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def point_a(self):
        """Gets the point_a of this InlineObject.

        Punto geografico di partenza  # noqa: E501

        :return: The point_a of this InlineObject.
        :rtype: str
        """
        return self._point_a

    @point_a.setter
    def point_a(self, point_a):
        """Sets the point_a of this InlineObject.

        Punto geografico di partenza  # noqa: E501

        :param point_a: The point_a of this InlineObject.
        :type point_a: str
        """

        self._point_a = point_a

    @property
    def points_b(self):
        """Gets the points_b of this InlineObject.

        Array di punti geografici di destinazione  # noqa: E501

        :return: The points_b of this InlineObject.
        :rtype: List[str]
        """
        return self._points_b

    @points_b.setter
    def points_b(self, points_b):
        """Sets the points_b of this InlineObject.

        Array di punti geografici di destinazione  # noqa: E501

        :param points_b: The points_b of this InlineObject.
        :type points_b: List[str]
        """

        self._points_b = points_b
