# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.inline_response200_distance import InlineResponse200Distance
from openapi_server import util

from openapi_server.models.inline_response200_distance import InlineResponse200Distance  # noqa: E501

class InlineResponse200(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, distance=None):  # noqa: E501
        """InlineResponse200 - a model defined in OpenAPI

        :param distance: The distance of this InlineResponse200.  # noqa: E501
        :type distance: List[InlineResponse200Distance]
        """
        self.openapi_types = {
            'distance': List[InlineResponse200Distance]
        }

        self.attribute_map = {
            'distance': 'distance'
        }

        self._distance = distance

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def distance(self):
        """Gets the distance of this InlineResponse200.


        :return: The distance of this InlineResponse200.
        :rtype: List[InlineResponse200Distance]
        """
        return self._distance

    @distance.setter
    def distance(self, distance):
        """Sets the distance of this InlineResponse200.


        :param distance: The distance of this InlineResponse200.
        :type distance: List[InlineResponse200Distance]
        """
        if distance is None:
            raise ValueError("Invalid value for `distance`, must not be `None`")  # noqa: E501
        if distance is not None and len(distance) < 1:
            raise ValueError("Invalid value for `distance`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._distance = distance
