openapi: 3.0.0
info:
  title: serviziBancariAPI
  version: '1.0'
  description: È l'API Restful offerta dal *fornitore dei servizi bancari* che rende accessibile la capability di generazione di un codice di pagamento con certi parametri e di ricevere dati relativi al pagamento di un cliente.
servers:
  - url: 'https://stoplight.io/mocks/soseng-unibo/soseng-project-documentation/7424070'
    description: testing
paths:
  /paymentdata:
    parameters: []
    post:
      summary: Ricevi dati di pagamento
      operationId: post-paymentdata
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              title: paymentDataBody
              type: object
              properties:
                card_number:
                  type: integer
                expiration:
                  type: object
                  properties:
                    month:
                      type: integer
                    year:
                      type: integer
                CVC:
                  type: integer
                circuit:
                  type: string
                transaction:
                  type: object
                  properties:
                    id:
                      type: string
                    date:
                      type: string
            examples:
              Esempio:
                value:
                  card_number: 1234123412341234
                  expiration:
                    month: 11
                    year: 2024
                  CVC: 123
                  circuit: maestro
                  transaction:
                    id: abcd12
                    date: '2020-03-05, 12:06 CET'
      description: È la risorsa che permette al cliente intenzionato ad acquistare un'offerta di inviare al fornitore dei servizi bancari il pagamento corrispondente.
      tags:
        - Risorse
      security:
        - apikey: []
      parameters: []
  /link:
    parameters: []
    post:
      summary: Genera link di pagamento
      operationId: get-link
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: activelink
                properties:
                  link:
                    type: string
              examples:
                Esempio:
                  value:
                    link: 123ayshgga

        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      security:
        - apikey: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: object
                  properties:
                    value:
                      type: number
                    currency:
                      type: string
                offer_code:
                  type: string
                  description: |-
                    Codice dell'offerta che il cliente intende acquistare: in dettaglio, questo codice non è quello identificante la coppia offerta - cliente, bensì è quello assegnato, in principio, all'offerta dalla compagnia aerea che l'ha attivata, ancor prima di comunicarla ad ACMESky.

                    Quando il fornitore dei servizi bancari inoltrerà la quota del pagamento del cliente alla compagnia aerea, le invierà anche questo codice per comunicarle l'offerta di cui le sta inviando il pagamento.
                airline:
                  type: string
                  description: 'Compagnia aerea che ha attivato l''offerta per il cui pagamento si chiede la generazione del link: servirà al fornitore dei servizi bancari per inoltrarle la quota spettante.'
            examples:
              Esempio:
                value:
                  amount:
                    value: 100
                    currency: €
                  offer_code: abcd123
                  airline: ryanair
        description: ''
      description: 'È la risorsa che, a fronte di una richiesta HTTP nella cui intestazione vi è un `token` identificativo valido, restituisce un codice di pagamento relativo all''offerta specificata.'
      tags:
        - Risorse
  /registration:
    post:
      summary: Registra un nuovo utente
      operationId: post-registration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: PaymentRegistration
                properties:
                  token:
                    type: string
              examples:
                Esempio:
                  value:
                    token: bWFnZ2llOnN1bW1lcnM=
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      description: È la risorsa che permette a chi intende interagire con il fornitore dei servizi bancari di ottenere l'APIKey per poter essere identificato e autorizzato.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Maps.v1_Credentials'
            examples:
              Esempio:
                value:
                  username: Mario
                  password: 1245a5a
      tags:
        - Risorse
components:
  schemas:
    Maps.v1_Credentials:
      title: credentials
      type: object
      properties:
        username:
          type: string
        password:
          type: string
  securitySchemes:
    apikey:
      name: apikey
      type: apiKey
      in: header
      description: Questo schema di sicurezza è stato impostato al fine di permettere esclusivamente ad ACMESky di richiedere alla banca la generazione del link di pagamento per una certa offerta.
  parameters:
    AuthorizationAPIKey:
      name: AuthorizationAPIKey
      in: header
      required: true
      schema:
        type: string
      description: Il valore deve essere il token che il cliente ha ricevuto durante la registrazione.
