# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LMflightFlightPrice(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, amount: float=None, currency: str=None):  # noqa: E501
        """LMflightFlightPrice - a model defined in Swagger

        :param amount: The amount of this LMflightFlightPrice.  # noqa: E501
        :type amount: float
        :param currency: The currency of this LMflightFlightPrice.  # noqa: E501
        :type currency: str
        """
        self.swagger_types = {
            'amount': float,
            'currency': str
        }

        self.attribute_map = {
            'amount': 'amount',
            'currency': 'currency'
        }
        self._amount = amount
        self._currency = currency

    @classmethod
    def from_dict(cls, dikt) -> 'LMflightFlightPrice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LMflight_flight_price of this LMflightFlightPrice.  # noqa: E501
        :rtype: LMflightFlightPrice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount(self) -> float:
        """Gets the amount of this LMflightFlightPrice.


        :return: The amount of this LMflightFlightPrice.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount: float):
        """Sets the amount of this LMflightFlightPrice.


        :param amount: The amount of this LMflightFlightPrice.
        :type amount: float
        """

        self._amount = amount

    @property
    def currency(self) -> str:
        """Gets the currency of this LMflightFlightPrice.


        :return: The currency of this LMflightFlightPrice.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency: str):
        """Sets the currency of this LMflightFlightPrice.


        :param currency: The currency of this LMflightFlightPrice.
        :type currency: str
        """

        self._currency = currency
