# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.l_mflight_flight import LMflightFlight  # noqa: F401,E501
from swagger_server import util


class Lmflight(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, flight: LMflightFlight=None, companyname: str=None):  # noqa: E501
        """Lmflight - a model defined in Swagger

        :param flight: The flight of this Lmflight.  # noqa: E501
        :type flight: LMflightFlight
        :param companyname: The companyname of this Lmflight.  # noqa: E501
        :type companyname: str
        """
        self.swagger_types = {
            'flight': LMflightFlight,
            'companyname': str
        }

        self.attribute_map = {
            'flight': 'flight',
            'companyname': 'companyname'
        }
        self._flight = flight
        self._companyname = companyname

    @classmethod
    def from_dict(cls, dikt) -> 'Lmflight':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The lmflight of this Lmflight.  # noqa: E501
        :rtype: Lmflight
        """
        return util.deserialize_model(dikt, cls)

    @property
    def flight(self) -> LMflightFlight:
        """Gets the flight of this Lmflight.


        :return: The flight of this Lmflight.
        :rtype: LMflightFlight
        """
        return self._flight

    @flight.setter
    def flight(self, flight: LMflightFlight):
        """Sets the flight of this Lmflight.


        :param flight: The flight of this Lmflight.
        :type flight: LMflightFlight
        """

        self._flight = flight

    @property
    def companyname(self) -> str:
        """Gets the companyname of this Lmflight.


        :return: The companyname of this Lmflight.
        :rtype: str
        """
        return self._companyname

    @companyname.setter
    def companyname(self, companyname: str):
        """Sets the companyname of this Lmflight.


        :param companyname: The companyname of this Lmflight.
        :type companyname: str
        """

        self._companyname = companyname
