/*
 * compagniaAereaAPI
 * È l'API Restful offerta dalla compagnia aerea che permette di restituire le offerte attive, creare voli last minute e di ricevere la quota del pagamento del cliente.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package airline.airline_client;

import airline.ApiException;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse2001;
import io.swagger.client.model.Lmflight;
import io.swagger.client.model.MapsV1Credentials;
import io.swagger.client.model.NotifypaymentBody;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RisorseApi
 */
@Ignore
public class RisorseApiTest {

    private final RisorseApi api = new RisorseApi();

    /**
     * Restituisci le offerte attive
     *
     * È la risorsa che restituisce tutte le offerte di voli attive, compresi i voli last minute.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFlightsTest() throws ApiException {
        InlineResponse200 response = api.getFlights();

        // TODO: test validations
    }
    /**
     * Crea un volo last minute
     *
     * Endpoint che permette di creare un volo lastminute, specificando tutti i parametri del volo; il server lo inoltrerà poi ad acmesky
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postLmflightTest() throws ApiException {
        Lmflight body = null;
        api.postLmflight(body);

        // TODO: test validations
    }
    /**
     * Ricevi pagamento
     *
     * È la risorsa che permette al fornitore dei servizi bancari di inviare alla compagnia aerea la quota del pagamento ricevuto dal cliente per l&#x27;acquisto dell&#x27;offerta.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postNotifypaymentTest() throws ApiException {
        NotifypaymentBody body = null;
        api.postNotifypayment(body);

        // TODO: test validations
    }
    /**
     * Registra un nuovo utente
     *
     * È la risorsa che permette a chi intende interagire con la compagnia aerea di ottenere l&#x27;APIKey per poter essere identificato e autorizzato.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postRegistrationTest() throws ApiException {
        MapsV1Credentials body = null;
        InlineResponse2001 response = api.postRegistration(body);

        // TODO: test validations
    }
}
