# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.link_amount import LinkAmount  # noqa: F401,E501
from swagger_server import util


class LinkBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, amount: LinkAmount=None, offer_code: str=None, airline: str=None):  # noqa: E501
        """LinkBody - a model defined in Swagger

        :param amount: The amount of this LinkBody.  # noqa: E501
        :type amount: LinkAmount
        :param offer_code: The offer_code of this LinkBody.  # noqa: E501
        :type offer_code: str
        :param airline: The airline of this LinkBody.  # noqa: E501
        :type airline: str
        """
        self.swagger_types = {
            'amount': LinkAmount,
            'offer_code': str,
            'airline': str
        }

        self.attribute_map = {
            'amount': 'amount',
            'offer_code': 'offer_code',
            'airline': 'airline'
        }
        self._amount = amount
        self._offer_code = offer_code
        self._airline = airline

    @classmethod
    def from_dict(cls, dikt) -> 'LinkBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The link_body of this LinkBody.  # noqa: E501
        :rtype: LinkBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount(self) -> LinkAmount:
        """Gets the amount of this LinkBody.


        :return: The amount of this LinkBody.
        :rtype: LinkAmount
        """
        return self._amount

    @amount.setter
    def amount(self, amount: LinkAmount):
        """Sets the amount of this LinkBody.


        :param amount: The amount of this LinkBody.
        :type amount: LinkAmount
        """

        self._amount = amount

    @property
    def offer_code(self) -> str:
        """Gets the offer_code of this LinkBody.

        Codice dell'offerta che il cliente intende acquistare: in dettaglio, questo codice non è quello identificante la coppia offerta - cliente, bensì è quello assegnato, in principio, all'offerta dalla compagnia aerea che l'ha attivata, ancor prima di comunicarla ad ACMESky.  Quando il fornitore dei servizi bancari inoltrerà la quota del pagamento del cliente alla compagnia aerea, le invierà anche questo codice per comunicarle l'offerta di cui le sta inviando il pagamento.  # noqa: E501

        :return: The offer_code of this LinkBody.
        :rtype: str
        """
        return self._offer_code

    @offer_code.setter
    def offer_code(self, offer_code: str):
        """Sets the offer_code of this LinkBody.

        Codice dell'offerta che il cliente intende acquistare: in dettaglio, questo codice non è quello identificante la coppia offerta - cliente, bensì è quello assegnato, in principio, all'offerta dalla compagnia aerea che l'ha attivata, ancor prima di comunicarla ad ACMESky.  Quando il fornitore dei servizi bancari inoltrerà la quota del pagamento del cliente alla compagnia aerea, le invierà anche questo codice per comunicarle l'offerta di cui le sta inviando il pagamento.  # noqa: E501

        :param offer_code: The offer_code of this LinkBody.
        :type offer_code: str
        """

        self._offer_code = offer_code

    @property
    def airline(self) -> str:
        """Gets the airline of this LinkBody.

        Compagnia aerea che ha attivato l'offerta per il cui pagamento si chiede la generazione del link: servirà al fornitore dei servizi bancari per inoltrarle la quota spettante.  # noqa: E501

        :return: The airline of this LinkBody.
        :rtype: str
        """
        return self._airline

    @airline.setter
    def airline(self, airline: str):
        """Sets the airline of this LinkBody.

        Compagnia aerea che ha attivato l'offerta per il cui pagamento si chiede la generazione del link: servirà al fornitore dei servizi bancari per inoltrarle la quota spettante.  # noqa: E501

        :param airline: The airline of this LinkBody.
        :type airline: str
        """

        self._airline = airline
