# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PaymentdataExpiration(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, month: int=None, year: int=None):  # noqa: E501
        """PaymentdataExpiration - a model defined in Swagger

        :param month: The month of this PaymentdataExpiration.  # noqa: E501
        :type month: int
        :param year: The year of this PaymentdataExpiration.  # noqa: E501
        :type year: int
        """
        self.swagger_types = {
            'month': int,
            'year': int
        }

        self.attribute_map = {
            'month': 'month',
            'year': 'year'
        }
        self._month = month
        self._year = year

    @classmethod
    def from_dict(cls, dikt) -> 'PaymentdataExpiration':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The paymentdata_expiration of this PaymentdataExpiration.  # noqa: E501
        :rtype: PaymentdataExpiration
        """
        return util.deserialize_model(dikt, cls)

    @property
    def month(self) -> int:
        """Gets the month of this PaymentdataExpiration.


        :return: The month of this PaymentdataExpiration.
        :rtype: int
        """
        return self._month

    @month.setter
    def month(self, month: int):
        """Sets the month of this PaymentdataExpiration.


        :param month: The month of this PaymentdataExpiration.
        :type month: int
        """

        self._month = month

    @property
    def year(self) -> int:
        """Gets the year of this PaymentdataExpiration.


        :return: The year of this PaymentdataExpiration.
        :rtype: int
        """
        return self._year

    @year.setter
    def year(self, year: int):
        """Sets the year of this PaymentdataExpiration.


        :param year: The year of this PaymentdataExpiration.
        :type year: int
        """

        self._year = year
