# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.offer_message import OfferMessage  # noqa: F401,E501
from swagger_server import util


class CreatemessageData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, receiver: str=None, offer: OfferMessage=None):  # noqa: E501
        """CreatemessageData - a model defined in Swagger

        :param receiver: The receiver of this CreatemessageData.  # noqa: E501
        :type receiver: str
        :param offer: The offer of this CreatemessageData.  # noqa: E501
        :type offer: OfferMessage
        """
        self.swagger_types = {
            'receiver': str,
            'offer': OfferMessage
        }

        self.attribute_map = {
            'receiver': 'receiver',
            'offer': 'offer'
        }
        self._receiver = receiver
        self._offer = offer

    @classmethod
    def from_dict(cls, dikt) -> 'CreatemessageData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The createmessage_data of this CreatemessageData.  # noqa: E501
        :rtype: CreatemessageData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def receiver(self) -> str:
        """Gets the receiver of this CreatemessageData.


        :return: The receiver of this CreatemessageData.
        :rtype: str
        """
        return self._receiver

    @receiver.setter
    def receiver(self, receiver: str):
        """Sets the receiver of this CreatemessageData.


        :param receiver: The receiver of this CreatemessageData.
        :type receiver: str
        """

        self._receiver = receiver

    @property
    def offer(self) -> OfferMessage:
        """Gets the offer of this CreatemessageData.


        :return: The offer of this CreatemessageData.
        :rtype: OfferMessage
        """
        return self._offer

    @offer.setter
    def offer(self, offer: OfferMessage):
        """Sets the offer of this CreatemessageData.


        :param offer: The offer of this CreatemessageData.
        :type offer: OfferMessage
        """

        self._offer = offer
